FROM oven/bun:1.1-alpine AS base

# Resetar repositórios para o padrão caso o sed tenha falhado
RUN echo "https://dl-cdn.alpinelinux.org/alpine/v3.20/main" > /etc/apk/repositories && \
    echo "https://dl-cdn.alpinelinux.org/alpine/v3.20/community" >> /etc/apk/repositories

# Instalar dependências para o Tauri
RUN apk add --no-cache \
    libsoup-dev \
    webkit2gtk-dev \
    gtk+3.0-dev \
    curl \
    wget \
    pkgconfig \
    build-base \
    openssl-dev

# Instalar Rust (necessário para o core do Tauri v2)
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /app

# Garantir o uso do lockfile binário do Bun
COPY package.json bun.lockb* ./
RUN bun install

COPY . .

EXPOSE 1420
CMD ["bun", "run", "dev"]
